import type { District } from '../types/dashboard';

// Realistic mock data for Northeast India Districts
// Note: currentRisk, confidence, riskDataStatus, environmental are overwritten by live ML pipeline in App.tsx
const DISTRICT_DATA: Record<string, Partial<District>> = {
  tawang: {
    id: 'tawang',
    name: 'Tawang District',
    state: 'Arunachal Pradesh',
    center: [27.5861, 91.8660],
    zoom: 12,
    currentRisk: 72,
    riskLevel: 'HIGH',
    riskTrend: '+14% from yesterday',
    predictionWindow: 'High risk possible within 4–8 hours',
    confidence: 89,
    criticalAlertsCount: 3,
    highRiskZonesCount: 7,
    blockedRoadsCount: 4,
    environmental: {
      rainfall24h: 92,
      soilMoisture: 78,
      temperature: 18,
      groundMovement: 1.2,
      humidity: 86,
      windSpeed: 14,
    },
    explainability: [
      {
        factor: 'Rainfall',
        percentage: 32,
        metricValue: '92 mm / 24h (Monsoon Surge)',
        category: 'rainfall',
        impact: 'high',
      },
      {
        factor: 'Soil Moisture',
        percentage: 24,
        metricValue: '78% Saturation Index',
        category: 'soil',
        impact: 'high',
      },
      {
        factor: 'Slope',
        percentage: 18,
        metricValue: '41° Critical Incline',
        category: 'slope',
        impact: 'high',
      },
      {
        factor: 'Ground Movement',
        percentage: 11,
        metricValue: '1.2 mm/hr Inclinometer Drift',
        category: 'movement',
        impact: 'moderate',
      },
      {
        factor: 'Historical Activity',
        percentage: 7,
        metricValue: '7 Events Recorded in 5 Yrs',
        category: 'historical',
        impact: 'moderate',
      },
    ],
    recommendedActions: [
      {
        id: 'act-1',
        priority: 1,
        title: 'Inspect Tawang Sector 12',
        location: 'Tawang Sector 12 (Upper Ridge)',
        status: 'Pending dispatch',
        actionType: 'INSPECT',
        description: 'Deploy quick response geotechnical team to verify subsurface crack dilation near residential terrace.',
        assignedAgency: 'PWD Geotechnical & NDRF Unit 4',
        targetCompletion: 'Immediate (< 2 hrs)',
      },
      {
        id: 'act-2',
        priority: 2,
        title: 'Monitor NH-13',
        location: 'NH-13 Km 42-48 (Jaswant Garh Pass)',
        status: 'Patrol active',
        actionType: 'MONITOR',
        description: 'BRO Task Force Himank currently clearing debris with continuous drone surveillance of upper crest.',
        assignedAgency: 'Border Roads Organisation (BRO)',
        targetCompletion: 'Continuous 24h Watch',
      },
      {
        id: 'act-3',
        priority: 3,
        title: 'Prepare nearby evacuation center',
        location: 'Tawang Town Hall Community Shelter B',
        status: 'Standby',
        actionType: 'PREPARE_EVACUATION',
        description: 'Stage emergency medical supplies, water rations, and emergency diesel power for up to 250 evacuees.',
        assignedAgency: 'District Disaster Management Authority (DDMA)',
        targetCompletion: 'Within 4 hrs',
      },
    ],
    riskZones: [
      {
        id: 'zone-12',
        name: 'Tawang Sector 12',
        sectorCode: 'TAW-SEC-12',
        riskScore: 87,
        riskLevel: 'HIGH',
        rainfall24h: 92,
        soilMoisture: 78,
        slopeAngle: 41,
        historicalEvents: 7,
        predictionWindow: '4–8 hours',
        confidence: 91,
        coordinates: [
          [27.5920, 91.8540],
          [27.5985, 91.8680],
          [27.5890, 91.8790],
          [27.5810, 91.8650],
          [27.5870, 91.8510],
        ],
        center: [27.5895, 91.8635],
        elevation: 3048,
        description: 'Steep colluvial slope above township ring road with high saturation from antecedent precipitation.',
        sensorsCount: 6,
        populationAtRisk: 1420,
        nearestFacility: 'District Civil Hospital Tawang (1.4 km)',
      },
      {
        id: 'zone-sela',
        name: 'Sela Pass North Corridor',
        sectorCode: 'TAW-SEC-01',
        riskScore: 89,
        riskLevel: 'CRITICAL',
        rainfall24h: 104,
        soilMoisture: 84,
        slopeAngle: 46,
        historicalEvents: 12,
        predictionWindow: '2–4 hours',
        confidence: 94,
        coordinates: [
          [27.5100, 92.0950],
          [27.5250, 92.1150],
          [27.5180, 92.1380],
          [27.4980, 92.1200],
          [27.5020, 92.0980],
        ],
        center: [27.5130, 92.1120],
        elevation: 4170,
        description: 'High altitude glacial till and unstable talus scree directly abutting the strategic highway.',
        sensorsCount: 8,
        populationAtRisk: 380,
        nearestFacility: 'BRO 42nd Task Post (2.1 km)',
      },
      {
        id: 'zone-lumla',
        name: 'Lumla Valley Slope B',
        sectorCode: 'TAW-SEC-05',
        riskScore: 74,
        riskLevel: 'HIGH',
        rainfall24h: 88,
        soilMoisture: 75,
        slopeAngle: 38,
        historicalEvents: 4,
        predictionWindow: '6–12 hours',
        confidence: 86,
        coordinates: [
          [27.5350, 91.7100],
          [27.5480, 91.7300],
          [27.5390, 91.7450],
          [27.5220, 91.7320],
          [27.5280, 91.7120],
        ],
        center: [27.5340, 91.7260],
        elevation: 2410,
        description: 'Terraced agricultural hillside showing active tension cracks along lower irrigation channels.',
        sensorsCount: 4,
        populationAtRisk: 890,
        nearestFacility: 'Lumla Sub-Divisional Hospital (0.8 km)',
      },
      {
        id: 'zone-jang',
        name: 'Jang Hydro Slopes',
        sectorCode: 'TAW-SEC-08',
        riskScore: 82,
        riskLevel: 'HIGH',
        rainfall24h: 95,
        soilMoisture: 80,
        slopeAngle: 43,
        historicalEvents: 6,
        predictionWindow: '4–8 hours',
        confidence: 88,
        coordinates: [
          [27.5750, 91.9800],
          [27.5890, 91.9950],
          [27.5810, 92.0150],
          [27.5650, 92.0020],
          [27.5680, 91.9820],
        ],
        center: [27.5760, 91.9970],
        elevation: 2190,
        description: 'Steep river gorge slopes near Nuranang power station with elevated pore water pressure.',
        sensorsCount: 5,
        populationAtRisk: 450,
        nearestFacility: 'Jang Community Health Center (1.9 km)',
      },
      {
        id: 'zone-mukto',
        name: 'Mukto Hillside Sector',
        sectorCode: 'TAW-SEC-09',
        riskScore: 68,
        riskLevel: 'WATCH',
        rainfall24h: 72,
        soilMoisture: 69,
        slopeAngle: 32,
        historicalEvents: 2,
        predictionWindow: '12–18 hours',
        confidence: 82,
        coordinates: [
          [27.5520, 91.9100],
          [27.5620, 91.9280],
          [27.5510, 91.9390],
          [27.5400, 91.9250],
        ],
        center: [27.5510, 91.9240],
        elevation: 2650,
        description: 'Vegetated slope with minor drainage overflow; monitored by acoustic emission sensor node.',
        sensorsCount: 3,
        populationAtRisk: 620,
        nearestFacility: 'Mukto First Aid Center (1.2 km)',
      },
      {
        id: 'zone-zimithang',
        name: 'Zimithang Highway Spur',
        sectorCode: 'TAW-SEC-14',
        riskScore: 79,
        riskLevel: 'HIGH',
        rainfall24h: 90,
        soilMoisture: 76,
        slopeAngle: 40,
        historicalEvents: 3,
        predictionWindow: '6–10 hours',
        confidence: 85,
        coordinates: [
          [27.7100, 91.7150],
          [27.7250, 91.7350],
          [27.7180, 91.7500],
          [27.7020, 91.7320],
        ],
        center: [27.7140, 91.7330],
        elevation: 2820,
        description: 'Active debris chute upstream of border post road with recurring rockfall.',
        sensorsCount: 4,
        populationAtRisk: 310,
        nearestFacility: 'ITBP Medical Post (2.4 km)',
      },
      {
        id: 'zone-kitpi',
        name: 'Kitpi Ridge Settlement',
        sectorCode: 'TAW-SEC-16',
        riskScore: 64,
        riskLevel: 'WATCH',
        rainfall24h: 65,
        soilMoisture: 63,
        slopeAngle: 29,
        historicalEvents: 1,
        predictionWindow: '18–24 hours',
        confidence: 79,
        coordinates: [
          [27.5950, 91.8200],
          [27.6080, 91.8350],
          [27.5990, 91.8480],
          [27.5870, 91.8340],
        ],
        center: [27.5970, 91.8340],
        elevation: 2710,
        description: 'Moderate slope settlement area; soil moisture stabilizing below critical threshold.',
        sensorsCount: 2,
        populationAtRisk: 740,
        nearestFacility: 'Kitpi Sub-Center (0.5 km)',
      },
    ],
    alerts: [
      {
        id: 'alt-1',
        title: 'Tawang Sector 12 Slumping Warning',
        location: 'Tawang Sector 12',
        riskScore: 94,
        severity: 'CRITICAL',
        timestamp: '2026-09-02T14:29:00Z',
        timeAgo: '8 minutes ago',
        summary: 'Inclinometer INC-04 detected 3.8mm displacement in past 30 minutes following sustained rain peak.',
        affectedRoads: ['Tawang Ring Road West', 'Sector 12 Feeder Road'],
        recommendedAction: 'Immediate preventive evacuation of lower 18 houses and heavy traffic diversion.',
        status: 'ACTIVE',
      },
      {
        id: 'alt-2',
        title: 'NH-13 Jaswant Garh Mudflow Hazard',
        location: 'NH-13 Corridor Km 46',
        riskScore: 81,
        severity: 'HIGH',
        timestamp: '2026-09-02T14:16:00Z',
        timeAgo: '21 minutes ago',
        summary: 'Culvert blockages causing rapid slope wash and localized mud deposition across two highway lanes.',
        affectedRoads: ['NH-13 Trans-Arunachal Highway'],
        recommendedAction: 'Deploy BRO earthmovers; restrict non-emergency vehicular movement.',
        status: 'ACTIVE',
      },
      {
        id: 'alt-3',
        title: 'Sela Pass North Talus Creep',
        location: 'Sela Pass North',
        riskScore: 68,
        severity: 'WATCH',
        timestamp: '2026-09-02T13:45:00Z',
        timeAgo: '52 minutes ago',
        summary: 'Piezometer levels at 84% capacity. Rockfall netting under elevated tension near curve 18.',
        affectedRoads: ['Sela Tunnel Northern Approach'],
        recommendedAction: 'Station BRO flag teams and maintain 20 km/h advisory speed limit.',
        status: 'ACTIVE',
      },
      {
        id: 'alt-4',
        title: 'Lumla Valley Road Debris Flow',
        location: 'Lumla Valley Km 12',
        riskScore: 76,
        severity: 'HIGH',
        timestamp: '2026-09-02T12:30:00Z',
        timeAgo: '2 hours ago',
        summary: 'Debris flow settled on single lane. PWD clearing operations ongoing.',
        affectedRoads: ['Tawang-Lumla Road'],
        recommendedAction: 'Single lane traffic control with spotters.',
        status: 'ACKNOWLEDGED',
      },
    ],
    roads: [
      {
        id: 'rd-1',
        name: 'NH-13 (Trans-Arunachal Highway - Jaswant Garh)',
        highwayCode: 'NH-13',
        status: 'BLOCKED',
        blockageReason: 'Major mudflow and boulder slide at Km 46.2',
        coordinates: [
          [27.5020, 92.0500],
          [27.5150, 92.0800],
          [27.5250, 92.1100],
          [27.5400, 92.1400],
        ],
        affectedLengthKm: 4.8,
        clearanceEstimate: '3–5 hours (BRO heavy machinery on site)',
        bypassAvailable: true,
        bypassRouteName: 'Old Military Bypass via Sela Lake Track (4x4 only)',
        lastUpdated: '12 mins ago',
      },
      {
        id: 'rd-2',
        name: 'Tawang-Lumla Arterial Road',
        highwayCode: 'SH-04',
        status: 'BLOCKED',
        blockageReason: 'Culvert collapse and earth slide near Km 18',
        coordinates: [
          [27.5850, 91.8600],
          [27.5600, 91.7900],
          [27.5350, 91.7250],
        ],
        affectedLengthKm: 2.1,
        clearanceEstimate: '6–8 hours',
        bypassAvailable: false,
        bypassRouteName: 'No standard bypass available',
        lastUpdated: '25 mins ago',
      },
      {
        id: 'rd-3',
        name: 'Sector 12 Ring Road Spur',
        highwayCode: 'UR-12',
        status: 'BLOCKED',
        blockageReason: 'Precautionary closure due to active slope dilation above road bed',
        coordinates: [
          [27.5880, 91.8550],
          [27.5940, 91.8640],
          [27.5920, 91.8720],
        ],
        affectedLengthKm: 1.2,
        clearanceEstimate: 'Pending geotechnical clearance inspection',
        bypassAvailable: true,
        bypassRouteName: 'Township Eastern Connector',
        lastUpdated: '8 mins ago',
      },
      {
        id: 'rd-4',
        name: 'Zimithang Border Road Km 9',
        highwayCode: 'BR-02',
        status: 'BLOCKED',
        blockageReason: 'Talus slide blocking both lanes near bridge approach',
        coordinates: [
          [27.6500, 91.7800],
          [27.6900, 91.7500],
          [27.7140, 91.7330],
        ],
        affectedLengthKm: 0.9,
        clearanceEstimate: '2 hours',
        bypassAvailable: false,
        bypassRouteName: 'No bypass',
        lastUpdated: '40 mins ago',
      },
      {
        id: 'rd-5',
        name: 'Tawang Town - Jang Bypass',
        highwayCode: 'SH-01',
        status: 'CLEAR',
        blockageReason: 'Clear with routine surface water drainage monitoring',
        coordinates: [
          [27.5860, 91.8700],
          [27.5750, 91.9400],
          [27.5760, 91.9970],
        ],
        affectedLengthKm: 0,
        clearanceEstimate: 'Operational',
        bypassAvailable: true,
        bypassRouteName: 'Primary open corridor',
        lastUpdated: '5 mins ago',
      },
    ],
    sensors: [
      {
        id: 'sens-1',
        name: 'INC-TAW-04 (Inclinometer)',
        type: 'INCLINOMETER',
        coordinates: [27.5910, 91.8620],
        value: '1.24 mm/hr (Drift)',
        status: 'CRITICAL',
        battery: 94,
        lastPing: '30s ago',
      },
      {
        id: 'sens-2',
        name: 'RG-TAW-01 (Tipping Bucket Rain Gauge)',
        type: 'RAIN_GAUGE',
        coordinates: [27.5880, 91.8590],
        value: '92.4 mm / 24h',
        status: 'CRITICAL',
        battery: 98,
        lastPing: '1m ago',
      },
      {
        id: 'sens-3',
        name: 'SM-TAW-08 (Soil Moisture Probe)',
        type: 'SOIL_MOISTURE',
        coordinates: [27.5940, 91.8650],
        value: '78.2% Saturation',
        status: 'WARNING',
        battery: 89,
        lastPing: '2m ago',
      },
      {
        id: 'sens-4',
        name: 'PZ-SELA-02 (Piezometer)',
        type: 'PIEZOMETER',
        coordinates: [27.5140, 92.1100],
        value: '142 kPa (Pore Pressure)',
        status: 'CRITICAL',
        battery: 91,
        lastPing: '45s ago',
      },
      {
        id: 'sens-5',
        name: 'CK-JANG-01 (Optical Crackmeter)',
        type: 'CRACKMETER',
        coordinates: [27.5770, 91.9950],
        value: '0.4 mm dilation',
        status: 'WARNING',
        battery: 96,
        lastPing: '3m ago',
      },
    ],
    facilities: [
      {
        id: 'fac-1',
        name: 'District Civil Hospital Tawang',
        type: 'HOSPITAL',
        coordinates: [27.5885, 91.8695],
        capacity: 120,
        occupancy: 48,
        contact: '+91-3794-222214',
      },
      {
        id: 'fac-2',
        name: 'Tawang Community Evacuation Shelter B',
        type: 'EVACUATION_CENTER',
        coordinates: [27.5830, 91.8610],
        capacity: 250,
        occupancy: 20,
        contact: '+91-3794-224102',
      },
      {
        id: 'fac-3',
        name: 'NDRF 12th Bn Disaster Base Camp',
        type: 'DISASTER_BASE',
        coordinates: [27.5790, 91.8740],
        capacity: 80,
        occupancy: 65,
        contact: '+91-3794-223300',
      },
      {
        id: 'fac-4',
        name: 'BRO 42nd BRTF Jaswant Post',
        type: 'ARMY_CAMP',
        coordinates: [27.5180, 92.1180],
        capacity: 150,
        occupancy: 95,
        contact: 'Radio Channel 4 / Mil-Net',
      },
    ],
    fieldReports: [
      {
        id: 'fr-1',
        observerName: 'Tsering Dorjee',
        designation: 'PWD Assistant Engineer',
        location: 'Tawang Sector 12 Upper Terraces',
        coordinates: [27.5915, 91.8630],
        hazardType: 'Tension Crack Expansion & Surface Mud Oozing',
        severity: 'CRITICAL',
        timeAgo: '14 minutes ago',
        notes: 'Continuous heavy rainfall causing runoff to channel into newly formed ground fissure (~15m length). Recommended cordoning off lane 3.',
        hasPhotos: true,
        photoCount: 4,
        verified: true,
      },
      {
        id: 'fr-2',
        observerName: 'Major K. Sharma',
        designation: 'BRO Officer-in-Charge, Project Vartak',
        location: 'NH-13 Km 46.2 (Jaswant Garh)',
        coordinates: [27.5145, 92.1080],
        hazardType: 'Overburden Slump onto Highway Bed',
        severity: 'HIGH',
        timeAgo: '32 minutes ago',
        notes: 'Approximately 400 cubic meters of mud and stone on road. 2 excavators and 1 wheel loader deployed. Intermittent rockfall slowing operations.',
        hasPhotos: true,
        photoCount: 3,
        verified: true,
      },
      {
        id: 'fr-3',
        observerName: 'Lobsang Norbu',
        designation: 'DDMA Field Volunteer',
        location: 'Lumla Bypass km 14',
        coordinates: [27.5380, 91.7320],
        hazardType: 'Minor Retaining Wall Bulging',
        severity: 'WATCH',
        timeAgo: '1 hour ago',
        notes: 'Stone masonry retaining wall showing 2-degree outward tilt; weep holes draining brown turbid water.',
        hasPhotos: true,
        photoCount: 2,
        verified: true,
      },
    ],
    trend24h: [
      { time: '14:00 (Y)', risk: 58, rainfall: 12, threshold: 70 },
      { time: '17:00', risk: 59, rainfall: 18, threshold: 70 },
      { time: '20:00', risk: 62, rainfall: 28, threshold: 70 },
      { time: '23:00', risk: 64, rainfall: 42, threshold: 70 },
      { time: '02:00', risk: 66, rainfall: 58, threshold: 70 },
      { time: '05:00', risk: 67, rainfall: 68, threshold: 70 },
      { time: '08:00', risk: 69, rainfall: 78, threshold: 70 },
      { time: '11:00', risk: 71, rainfall: 86, threshold: 70 },
      { time: '14:00 (Now)', risk: 72, rainfall: 92, threshold: 70 },
    ],
  },
  gangtok: {
    id: 'gangtok',
    name: 'Gangtok District',
    state: 'Sikkim',
    center: [27.3389, 88.6065],
    zoom: 12,
    currentRisk: 66,
    riskLevel: 'WATCH',
    riskTrend: '+6% from yesterday',
    predictionWindow: 'Elevated watch over next 12 hours',
    confidence: 87,
    criticalAlertsCount: 2,
    highRiskZonesCount: 5,
    blockedRoadsCount: 2,
    environmental: {
      rainfall24h: 68,
      soilMoisture: 71,
      temperature: 17,
      groundMovement: 0.7,
      humidity: 82,
      windSpeed: 11,
    },
    explainability: [
      { factor: 'Rainfall', percentage: 28, metricValue: '68 mm / 24h', category: 'rainfall', impact: 'moderate' },
      { factor: 'Soil Moisture', percentage: 25, metricValue: '71% Saturation', category: 'soil', impact: 'moderate' },
      { factor: 'Slope', percentage: 21, metricValue: '37° Slopes', category: 'slope', impact: 'high' },
      { factor: 'Ground Movement', percentage: 14, metricValue: '0.7 mm/hr', category: 'movement', impact: 'moderate' },
      { factor: 'Historical Activity', percentage: 12, metricValue: '5 Past Events', category: 'historical', impact: 'moderate' },
    ],
    recommendedActions: [
      {
        id: 'act-g1',
        priority: 1,
        title: 'Inspect Burtuk Sinking Zone',
        location: 'NH-10 Burtuk Section',
        status: 'Patrol active',
        actionType: 'INSPECT',
        description: 'Monitor subsidence gauges on highway edge after prolonged rain.',
        assignedAgency: 'Sikkim State Disaster Management Authority',
        targetCompletion: 'Within 3 hrs',
      },
      {
        id: 'act-g2',
        priority: 2,
        title: 'Maintain Rani Pool Alert Status',
        location: 'Rani Pool Riverbank Slope',
        status: 'Standby',
        actionType: 'MONITOR',
        description: 'Verify river water levels and check for bank toe erosion.',
        assignedAgency: 'Irrigation & Flood Control Dept',
        targetCompletion: 'Ongoing',
      },
    ],
    riskZones: [
      {
        id: 'zone-g-burtuk',
        name: 'Burtuk Sinking Zone',
        sectorCode: 'GTK-SEC-03',
        riskScore: 78,
        riskLevel: 'HIGH',
        rainfall24h: 74,
        soilMoisture: 75,
        slopeAngle: 39,
        historicalEvents: 8,
        predictionWindow: '6–10 hours',
        confidence: 88,
        coordinates: [
          [27.3480, 88.6100],
          [27.3560, 88.6220],
          [27.3490, 88.6340],
          [27.3410, 88.6210],
        ],
        center: [27.3485, 88.6215],
        elevation: 1720,
        description: 'Historical chronic creeping landslide zone affecting the national highway connector.',
        sensorsCount: 5,
        populationAtRisk: 1100,
        nearestFacility: 'STNM Multispeciality Hospital (3.2 km)',
      },
      {
        id: 'zone-g-deorali',
        name: 'Deorali Ridge Face',
        sectorCode: 'GTK-SEC-07',
        riskScore: 65,
        riskLevel: 'WATCH',
        rainfall24h: 68,
        soilMoisture: 71,
        slopeAngle: 35,
        historicalEvents: 3,
        predictionWindow: '12–18 hours',
        confidence: 84,
        coordinates: [
          [27.3200, 88.6010],
          [27.3280, 88.6120],
          [27.3220, 88.6240],
          [27.3140, 88.6100],
        ],
        center: [27.3210, 88.6115],
        elevation: 1540,
        description: 'Urban slope with drainage canal retaining structures.',
        sensorsCount: 3,
        populationAtRisk: 1850,
        nearestFacility: 'District Disaster Operations Center (1.0 km)',
      },
    ],
    alerts: [
      {
        id: 'alt-g1',
        title: 'Burtuk Highway Subsidence Watch',
        location: 'NH-10 Burtuk Section',
        riskScore: 78,
        severity: 'HIGH',
        timestamp: '2026-09-02T13:50:00Z',
        timeAgo: '47 minutes ago',
        summary: 'Roadbed settlement of 15mm noted near culvert 4.',
        affectedRoads: ['NH-10 Gangtok-Siliguri Highway'],
        recommendedAction: 'Limit axle loads to 16 tonnes; active traffic marshaling.',
        status: 'ACTIVE',
      },
    ],
    roads: [
      {
        id: 'rd-g1',
        name: 'NH-10 Gangtok - Singtam Segment',
        highwayCode: 'NH-10',
        status: 'RESTRICTED',
        blockageReason: 'Single lane operation due to minor rockfall',
        coordinates: [
          [27.3300, 88.6000],
          [27.2800, 88.5500],
          [27.2300, 88.5000],
        ],
        affectedLengthKm: 1.5,
        clearanceEstimate: '1.5 hours',
        bypassAvailable: true,
        bypassRouteName: 'Via Dikchu - Mangan alternate',
        lastUpdated: '20 mins ago',
      },
    ],
    sensors: [
      {
        id: 'sens-g1',
        name: 'INC-GTK-01',
        type: 'INCLINOMETER',
        coordinates: [27.3485, 88.6215],
        value: '0.72 mm/hr',
        status: 'WARNING',
        battery: 92,
        lastPing: '1m ago',
      },
    ],
    facilities: [
      {
        id: 'fac-g1',
        name: 'STNM Multispeciality Hospital Gangtok',
        type: 'HOSPITAL',
        coordinates: [27.3250, 88.6080],
        capacity: 500,
        occupancy: 210,
        contact: '+91-3592-202944',
      },
    ],
    fieldReports: [
      {
        id: 'fr-g1',
        observerName: 'Pema Lepcha',
        designation: 'Road Inspector, BRO Swastik',
        location: 'Burtuk Mile 4',
        coordinates: [27.3500, 88.6200],
        hazardType: 'Surface Runoff Drainage Overflow',
        severity: 'WATCH',
        timeAgo: '1 hour ago',
        notes: 'Culvert inlet cleared of tree debris; flow normalized.',
        hasPhotos: true,
        photoCount: 1,
        verified: true,
      },
    ],
    trend24h: [
      { time: '14:00 (Y)', risk: 52, rainfall: 10, threshold: 70 },
      { time: '20:00', risk: 56, rainfall: 24, threshold: 70 },
      { time: '02:00', risk: 60, rainfall: 42, threshold: 70 },
      { time: '08:00', risk: 63, rainfall: 58, threshold: 70 },
      { time: '14:00 (Now)', risk: 66, rainfall: 68, threshold: 70 },
    ],
  },
  shillong: {
    id: 'shillong',
    name: 'East Khasi Hills (Shillong)',
    state: 'Meghalaya',
    center: [25.5788, 91.8933],
    zoom: 12,
    currentRisk: 58,
    riskLevel: 'WATCH',
    riskTrend: '-2% from yesterday',
    predictionWindow: 'Stable watch conditions',
    confidence: 85,
    criticalAlertsCount: 1,
    highRiskZonesCount: 3,
    blockedRoadsCount: 1,
    environmental: {
      rainfall24h: 54,
      soilMoisture: 62,
      temperature: 19,
      groundMovement: 0.4,
      humidity: 79,
      windSpeed: 16,
    },
    explainability: [
      { factor: 'Rainfall', percentage: 25, metricValue: '54 mm / 24h', category: 'rainfall', impact: 'moderate' },
      { factor: 'Soil Moisture', percentage: 22, metricValue: '62% Saturation', category: 'soil', impact: 'moderate' },
      { factor: 'Slope', percentage: 24, metricValue: '31° Escarpment', category: 'slope', impact: 'moderate' },
      { factor: 'Ground Movement', percentage: 15, metricValue: '0.4 mm/hr', category: 'movement', impact: 'low' },
      { factor: 'Historical Activity', percentage: 14, metricValue: '3 Past Events', category: 'historical', impact: 'low' },
    ],
    recommendedActions: [
      {
        id: 'act-s1',
        priority: 1,
        title: 'Check Umiam Bypass Slopes',
        location: 'Umiam Lake View Road',
        status: 'Pending dispatch',
        actionType: 'INSPECT',
        description: 'Verify slope stabilization geotextiles along newly widened highway curve.',
        assignedAgency: 'Meghalaya PWD (NH)',
        targetCompletion: 'Within 4 hrs',
      },
    ],
    riskZones: [
      {
        id: 'zone-s-umiam',
        name: 'Umiam Gorge Escarpment',
        sectorCode: 'SHL-SEC-02',
        riskScore: 68,
        riskLevel: 'WATCH',
        rainfall24h: 58,
        soilMoisture: 66,
        slopeAngle: 36,
        historicalEvents: 3,
        predictionWindow: '12–18 hours',
        confidence: 84,
        coordinates: [
          [25.6400, 91.9000],
          [25.6550, 91.9200],
          [25.6450, 91.9350],
          [25.6320, 91.9150],
        ],
        center: [25.6430, 91.9175],
        elevation: 1020,
        description: 'Quartzite bedrock with thin overburden soil above highway corridor.',
        sensorsCount: 3,
        populationAtRisk: 420,
        nearestFacility: 'NEIGRIHMS Super Care Hospital (6.5 km)',
      },
    ],
    alerts: [
      {
        id: 'alt-s1',
        title: 'Shillong Peak Road Slumping',
        location: 'Laitkor Peak Road',
        riskScore: 62,
        severity: 'WATCH',
        timestamp: '2026-09-02T11:15:00Z',
        timeAgo: '3 hours ago',
        summary: 'Small soil slip along outer road shoulder.',
        affectedRoads: ['Laitkor Peak Approach'],
        recommendedAction: 'Barricading and single lane signage.',
        status: 'ACTIVE',
      },
    ],
    roads: [
      {
        id: 'rd-s1',
        name: 'Shillong - Dawki Highway (NH-40)',
        highwayCode: 'NH-40',
        status: 'CLEAR',
        blockageReason: 'All lanes open',
        coordinates: [
          [25.5700, 91.8800],
          [25.4500, 91.8500],
        ],
        affectedLengthKm: 0,
        clearanceEstimate: 'Operational',
        bypassAvailable: true,
        bypassRouteName: 'Primary open corridor',
        lastUpdated: '10 mins ago',
      },
    ],
    sensors: [
      {
        id: 'sens-s1',
        name: 'RG-SHL-01',
        type: 'RAIN_GAUGE',
        coordinates: [25.5788, 91.8933],
        value: '54.2 mm / 24h',
        status: 'OPTIMAL',
        battery: 99,
        lastPing: '2m ago',
      },
    ],
    facilities: [
      {
        id: 'fac-s1',
        name: 'NEIGRIHMS Shillong',
        type: 'HOSPITAL',
        coordinates: [25.5920, 91.9380],
        capacity: 600,
        occupancy: 380,
        contact: '+91-364-2538011',
      },
    ],
    fieldReports: [
      {
        id: 'fr-s1',
        observerName: 'Banteilang Lyngdoh',
        designation: 'PWD Junior Engineer',
        location: 'Upper Shillong Km 8',
        coordinates: [25.5450, 91.8400],
        hazardType: 'Shoulder Erosion',
        severity: 'WATCH',
        timeAgo: '2 hours ago',
        notes: 'Sandbag reinforcement placed along 20m shoulder stretch.',
        hasPhotos: false,
        verified: true,
      },
    ],
    trend24h: [
      { time: '14:00 (Y)', risk: 60, rainfall: 35, threshold: 70 },
      { time: '20:00', risk: 61, rainfall: 42, threshold: 70 },
      { time: '02:00', risk: 59, rainfall: 48, threshold: 70 },
      { time: '08:00', risk: 58, rainfall: 52, threshold: 70 },
      { time: '14:00 (Now)', risk: 58, rainfall: 54, threshold: 70 },
    ],
  },
  kohima: {
    id: 'kohima',
    name: 'Kohima District',
    state: 'Nagaland',
    center: [25.6751, 94.1086],
    zoom: 12,
    currentRisk: 79,
    riskLevel: 'HIGH',
    riskTrend: '+18% from yesterday',
    predictionWindow: 'High risk escalation in next 3–6 hours',
    confidence: 90,
    criticalAlertsCount: 4,
    highRiskZonesCount: 8,
    blockedRoadsCount: 3,
    environmental: {
      rainfall24h: 112,
      soilMoisture: 82,
      temperature: 20,
      groundMovement: 1.6,
      humidity: 89,
      windSpeed: 12,
    },
    explainability: [
      { factor: 'Rainfall', percentage: 35, metricValue: '112 mm / 24h (Extreme Cloudburst)', category: 'rainfall', impact: 'high' },
      { factor: 'Soil Moisture', percentage: 26, metricValue: '82% Saturated Shale', category: 'soil', impact: 'high' },
      { factor: 'Slope', percentage: 17, metricValue: '39° Unconsolidated Strata', category: 'slope', impact: 'high' },
      { factor: 'Ground Movement', percentage: 14, metricValue: '1.6 mm/hr Creep', category: 'movement', impact: 'high' },
      { factor: 'Historical Activity', percentage: 8, metricValue: '9 Events in 4 Yrs', category: 'historical', impact: 'moderate' },
    ],
    recommendedActions: [
      {
        id: 'act-k1',
        priority: 1,
        title: 'Evacuate Dzüdza River Sinking Settlement',
        location: 'Dzüdza Bridge Approach',
        status: 'Pending dispatch',
        actionType: 'PREPARE_EVACUATION',
        description: 'Initiate swift evacuation for 32 hillside homes adjacent to major active subsidence fissure.',
        assignedAgency: 'Nagaland State Disaster Management Authority & SDRF',
        targetCompletion: 'Immediate (< 1 hr)',
      },
      {
        id: 'act-k2',
        priority: 2,
        title: 'Close NH-29 Kohima-Dimapur 4-Lane Segment',
        location: 'NH-29 Km 14 (Old KMC Dumping Area)',
        status: 'Patrol active',
        actionType: 'ROAD_CLOSURE',
        description: 'Divert all inter-state goods traffic via Jotsoma-Khonoma bypass.',
        assignedAgency: 'Traffic Police Kohima & NHIDCL',
        targetCompletion: 'Immediate',
      },
    ],
    riskZones: [
      {
        id: 'zone-k-dzudza',
        name: 'Dzüdza Active Subsidence Zone',
        sectorCode: 'KOH-SEC-01',
        riskScore: 92,
        riskLevel: 'CRITICAL',
        rainfall24h: 118,
        soilMoisture: 86,
        slopeAngle: 42,
        historicalEvents: 14,
        predictionWindow: '1–3 hours',
        confidence: 93,
        coordinates: [
          [25.6800, 94.0600],
          [25.6950, 94.0800],
          [25.6850, 94.0950],
          [25.6700, 94.0750],
        ],
        center: [25.6825, 94.0775],
        elevation: 1280,
        description: 'Extremely vulnerable Disang shale formation exhibiting massive rotational slide dynamics.',
        sensorsCount: 7,
        populationAtRisk: 1950,
        nearestFacility: 'Naga Hospital Authority Kohima (4.5 km)',
      },
    ],
    alerts: [
      {
        id: 'alt-k1',
        title: 'NH-29 Dzüdza Sinking Alert',
        location: 'Dzüdza River Bridge Km 14',
        riskScore: 96,
        severity: 'CRITICAL',
        timestamp: '2026-09-02T14:10:00Z',
        timeAgo: '27 minutes ago',
        summary: 'Massive landslide sheared lower bridge abutment foundation. Total road cutoff.',
        affectedRoads: ['NH-29 Kohima-Dimapur Lifeline'],
        recommendedAction: 'Immediate multi-agency emergency response and detour enforcement.',
        status: 'ACTIVE',
      },
    ],
    roads: [
      {
        id: 'rd-k1',
        name: 'NH-29 (Dimapur - Kohima Highway)',
        highwayCode: 'NH-29',
        status: 'BLOCKED',
        blockageReason: 'Major hill collapse across 120m highway stretch at Dzüdza',
        coordinates: [
          [25.7100, 93.9800],
          [25.6800, 94.0700],
          [25.6750, 94.1080],
        ],
        affectedLengthKm: 12.0,
        clearanceEstimate: '18–24 hours',
        bypassAvailable: true,
        bypassRouteName: 'Via Peducha - Tsiesema 10-Ton Bypass',
        lastUpdated: '15 mins ago',
      },
    ],
    sensors: [
      {
        id: 'sens-k1',
        name: 'INC-KOH-07',
        type: 'INCLINOMETER',
        coordinates: [25.6825, 94.0775],
        value: '2.1 mm/hr (Rapid Surge)',
        status: 'CRITICAL',
        battery: 95,
        lastPing: '20s ago',
      },
    ],
    facilities: [
      {
        id: 'fac-k1',
        name: 'Naga Hospital Authority Kohima (NHAK)',
        type: 'HOSPITAL',
        coordinates: [25.6720, 94.1050],
        capacity: 350,
        occupancy: 290,
        contact: '+91-370-2244111',
      },
    ],
    fieldReports: [
      {
        id: 'fr-k1',
        observerName: 'Vitolie Angami',
        designation: 'NSDMA Disaster Field Officer',
        location: 'Dzüdza Bridge Abutment',
        coordinates: [25.6820, 94.0770],
        hazardType: 'Catastrophic Mass Wasting',
        severity: 'CRITICAL',
        timeAgo: '22 minutes ago',
        notes: 'High water volume in river eroding toe of slide mass. NHIDCL heavy dozers standing by.',
        hasPhotos: true,
        photoCount: 5,
        verified: true,
      },
    ],
    trend24h: [
      { time: '14:00 (Y)', risk: 61, rainfall: 15, threshold: 70 },
      { time: '20:00', risk: 65, rainfall: 35, threshold: 70 },
      { time: '02:00', risk: 70, rainfall: 62, threshold: 70 },
      { time: '08:00', risk: 75, rainfall: 90, threshold: 70 },
      { time: '14:00 (Now)', risk: 79, rainfall: 112, threshold: 70 },
    ],
  },
  aizawl: {
    id: 'aizawl',
    name: 'Aizawl District',
    state: 'Mizoram',
    center: [23.7307, 92.7173],
    zoom: 12,
    currentRisk: 84,
    riskLevel: 'CRITICAL',
    riskTrend: '+22% from yesterday',
    predictionWindow: 'Critical landslide event expected within 2–4 hours',
    confidence: 92,
    criticalAlertsCount: 5,
    highRiskZonesCount: 9,
    blockedRoadsCount: 5,
    environmental: {
      rainfall24h: 138,
      soilMoisture: 88,
      temperature: 22,
      groundMovement: 2.3,
      humidity: 94,
      windSpeed: 18,
    },
    explainability: [
      { factor: 'Rainfall', percentage: 38, metricValue: '138 mm / 24h (Torrential Inundation)', category: 'rainfall', impact: 'high' },
      { factor: 'Soil Moisture', percentage: 27, metricValue: '88% Extreme Pore Pressure', category: 'soil', impact: 'high' },
      { factor: 'Slope', percentage: 16, metricValue: '44° Steep Ridge Flank', category: 'slope', impact: 'high' },
      { factor: 'Ground Movement', percentage: 13, metricValue: '2.3 mm/hr Rapid Creep', category: 'movement', impact: 'high' },
      { factor: 'Historical Activity', percentage: 6, metricValue: '11 Recent Slips', category: 'historical', impact: 'moderate' },
    ],
    recommendedActions: [
      {
        id: 'act-a1',
        priority: 1,
        title: 'Execute Immediate Evacuation at Laipuitlang Flank',
        location: 'Laipuitlang Hillside Sector',
        status: 'Pending dispatch',
        actionType: 'PREPARE_EVACUATION',
        description: 'High probability of catastrophic rockfall and colluvial slip. Sound district emergency sirens.',
        assignedAgency: 'Aizawl DDMA & SDRF 1st Bn',
        targetCompletion: 'Immediate (< 30 mins)',
      },
    ],
    riskZones: [
      {
        id: 'zone-a-laipuitlang',
        name: 'Laipuitlang Ridge Flank',
        sectorCode: 'AZL-SEC-01',
        riskScore: 95,
        riskLevel: 'CRITICAL',
        rainfall24h: 142,
        soilMoisture: 91,
        slopeAngle: 47,
        historicalEvents: 16,
        predictionWindow: '1–2 hours',
        confidence: 96,
        coordinates: [
          [23.7380, 92.7100],
          [23.7500, 92.7250],
          [23.7420, 92.7380],
          [23.7300, 92.7220],
        ],
        center: [23.7400, 92.7235],
        elevation: 1130,
        description: 'Heavily urbanized sandstone-shale ridge with severe groundwater buildup behind retaining walls.',
        sensorsCount: 9,
        populationAtRisk: 3100,
        nearestFacility: 'Civil Hospital Aizawl (1.2 km)',
      },
    ],
    alerts: [
      {
        id: 'alt-a1',
        title: 'Laipuitlang Fissure Critical Escalation',
        location: 'Laipuitlang Sector 1',
        riskScore: 98,
        severity: 'CRITICAL',
        timestamp: '2026-09-02T14:20:00Z',
        timeAgo: '17 minutes ago',
        summary: 'Acoustic emissions detect rock fracture propagation. Siren network activated.',
        affectedRoads: ['Aizawl North Spine Road'],
        recommendedAction: 'Immediate total exclusion zone setup.',
        status: 'ACTIVE',
      },
    ],
    roads: [
      {
        id: 'rd-a1',
        name: 'NH-54 (Aizawl - Silchar Corridor)',
        highwayCode: 'NH-54',
        status: 'BLOCKED',
        blockageReason: 'Multiple debris slides at 3 locations',
        coordinates: [
          [23.7300, 92.7150],
          [23.8200, 92.7500],
        ],
        affectedLengthKm: 14.5,
        clearanceEstimate: '12 hours',
        bypassAvailable: false,
        bypassRouteName: 'None',
        lastUpdated: '10 mins ago',
      },
    ],
    sensors: [
      {
        id: 'sens-a1',
        name: 'INC-AZL-09',
        type: 'INCLINOMETER',
        coordinates: [23.7400, 92.7235],
        value: '2.8 mm/hr (Surge)',
        status: 'CRITICAL',
        battery: 98,
        lastPing: '15s ago',
      },
    ],
    facilities: [
      {
        id: 'fac-a1',
        name: 'Civil Hospital Aizawl',
        type: 'HOSPITAL',
        coordinates: [23.7350, 92.7180],
        capacity: 400,
        occupancy: 340,
        contact: '+91-389-2322318',
      },
    ],
    fieldReports: [
      {
        id: 'fr-a1',
        observerName: 'Lalrinsanga',
        designation: 'Mizoram Geological Survey Field Tech',
        location: 'Laipuitlang Upper Road',
        coordinates: [23.7410, 92.7240],
        hazardType: 'Building Foundation Cracking & Heave',
        severity: 'CRITICAL',
        timeAgo: '12 minutes ago',
        notes: 'Three multi-story residential buildings showing structural shear cracks. Evacuation order in progress.',
        hasPhotos: true,
        photoCount: 6,
        verified: true,
      },
    ],
    trend24h: [
      { time: '14:00 (Y)', risk: 62, rainfall: 22, threshold: 70 },
      { time: '20:00', risk: 68, rainfall: 54, threshold: 70 },
      { time: '02:00', risk: 74, rainfall: 88, threshold: 70 },
      { time: '08:00', risk: 80, rainfall: 115, threshold: 70 },
      { time: '14:00 (Now)', risk: 84, rainfall: 138, threshold: 70 },
    ],
  },
  itanagar: {
    id: 'itanagar',
    name: 'Papum Pare (Itanagar)',
    state: 'Arunachal Pradesh',
    center: [27.0844, 93.6053],
    zoom: 12,
    currentRisk: 45,
    riskLevel: 'SAFE',
    riskTrend: '-8% from yesterday',
    predictionWindow: 'Nominal baseline conditions',
    confidence: 88,
    criticalAlertsCount: 0,
    highRiskZonesCount: 2,
    blockedRoadsCount: 0,
    environmental: {
      rainfall24h: 22,
      soilMoisture: 48,
      temperature: 26,
      groundMovement: 0.1,
      humidity: 68,
      windSpeed: 8,
    },
    explainability: [
      { factor: 'Rainfall', percentage: 18, metricValue: '22 mm / 24h (Light Showers)', category: 'rainfall', impact: 'low' },
      { factor: 'Soil Moisture', percentage: 20, metricValue: '48% Saturation', category: 'soil', impact: 'low' },
      { factor: 'Slope', percentage: 28, metricValue: '26° Foothill Gradient', category: 'slope', impact: 'low' },
      { factor: 'Ground Movement', percentage: 18, metricValue: '0.1 mm/hr (Stable)', category: 'movement', impact: 'low' },
      { factor: 'Historical Activity', percentage: 16, metricValue: '1 Historical Slip', category: 'historical', impact: 'low' },
    ],
    recommendedActions: [
      {
        id: 'act-i1',
        priority: 1,
        title: 'Routine Sensor Health Inspection',
        location: 'Ganga Lake Watershed Sensors',
        status: 'Standby',
        actionType: 'MONITOR',
        description: 'Verify solar panel dust clean and battery cycle telemetry.',
        assignedAgency: 'Arunachal State Remote Sensing Application Centre',
        targetCompletion: 'Within 24 hrs',
      },
    ],
    riskZones: [
      {
        id: 'zone-i-ganga',
        name: 'Ganga Lake Catchment Slope',
        sectorCode: 'ITA-SEC-02',
        riskScore: 48,
        riskLevel: 'SAFE',
        rainfall24h: 24,
        soilMoisture: 50,
        slopeAngle: 28,
        historicalEvents: 1,
        predictionWindow: 'No immediate alert',
        confidence: 89,
        coordinates: [
          [27.0700, 93.5800],
          [27.0850, 93.6000],
          [27.0780, 93.6150],
          [27.0650, 93.5950],
        ],
        center: [27.0745, 93.5975],
        elevation: 650,
        description: 'Dense sub-tropical forest cover providing root tensile cohesion.',
        sensorsCount: 3,
        populationAtRisk: 120,
        nearestFacility: 'TRIHMS Hospital Naharlagun (8.2 km)',
      },
    ],
    alerts: [],
    roads: [
      {
        id: 'rd-i1',
        name: 'NH-415 (Itanagar - Naharlagun Highway)',
        highwayCode: 'NH-415',
        status: 'CLEAR',
        blockageReason: 'All 4 lanes clear and operational',
        coordinates: [
          [27.0844, 93.6053],
          [27.1050, 93.6800],
        ],
        affectedLengthKm: 0,
        clearanceEstimate: 'Clear',
        bypassAvailable: true,
        bypassRouteName: 'Jully Bypass Road',
        lastUpdated: '5 mins ago',
      },
    ],
    sensors: [
      {
        id: 'sens-i1',
        name: 'RG-ITA-01',
        type: 'RAIN_GAUGE',
        coordinates: [27.0844, 93.6053],
        value: '22.0 mm / 24h',
        status: 'OPTIMAL',
        battery: 100,
        lastPing: '1m ago',
      },
    ],
    facilities: [
      {
        id: 'fac-i1',
        name: 'Tomo Riba Institute of Health (TRIHMS)',
        type: 'HOSPITAL',
        coordinates: [27.1080, 93.6850],
        capacity: 500,
        occupancy: 220,
        contact: '+91-360-2244256',
      },
    ],
    fieldReports: [],
    trend24h: [
      { time: '14:00 (Y)', risk: 53, rainfall: 40, threshold: 70 },
      { time: '20:00', risk: 50, rainfall: 32, threshold: 70 },
      { time: '02:00', risk: 48, rainfall: 28, threshold: 70 },
      { time: '08:00', risk: 46, rainfall: 24, threshold: 70 },
      { time: '14:00 (Now)', risk: 45, rainfall: 22, threshold: 70 },
    ],
  },
};

// Available District list for switching
export const AVAILABLE_DISTRICTS = [
  { id: 'tawang', name: 'Tawang District', state: 'Arunachal Pradesh', risk: 72, riskLevel: 'HIGH' as const },
  { id: 'gangtok', name: 'Gangtok District', state: 'Sikkim', risk: 66, riskLevel: 'WATCH' as const },
  { id: 'shillong', name: 'East Khasi Hills (Shillong)', state: 'Meghalaya', risk: 58, riskLevel: 'WATCH' as const },
  { id: 'kohima', name: 'Kohima District', state: 'Nagaland', risk: 79, riskLevel: 'HIGH' as const },
  { id: 'aizawl', name: 'Aizawl District', state: 'Mizoram', risk: 84, riskLevel: 'CRITICAL' as const },
  { id: 'itanagar', name: 'Papum Pare (Itanagar)', state: 'Arunachal Pradesh', risk: 45, riskLevel: 'SAFE' as const },
];

/**
 * Service Layer for LANDGUARD AI Dashboard.
 */
export const dashboardService = {
  async getDistrictData(districtId: string = 'tawang'): Promise<Partial<District>> {
    await new Promise((resolve) => setTimeout(resolve, 60));
    return DISTRICT_DATA[districtId] || DISTRICT_DATA['tawang'];
  },

  async triggerEmergencyAlert(_payload: {
    zoneId: string;
    zoneName: string;
    severity: string;
    channels: string[];
    message: string;
  }): Promise<{ success: boolean; broadcastId: string; dispatchedAt: string }> {
    await new Promise((resolve) => setTimeout(resolve, 400));
    return {
      success: true,
      broadcastId: `CAP-IN-NE-${Date.now().toString().slice(-6)}`,
      dispatchedAt: new Date().toISOString(),
    };
  },

  async updateActionStatus(_actionId: string, _status: string): Promise<boolean> {
    await new Promise((resolve) => setTimeout(resolve, 200));
    return true;
  },
};
